### ISSUE TITLE
Random crash when setting joypad controls

### ISSUE THREAD

**Issue by kabili207** [Arisotura/melonDS#284]
MelonDS  seems to crash at random when I try to update the joypad controls. Sometimes I can get one or two buttons set before it crashes, other times it crashes immediately. The error seems to be occurring somewhere in GTK, so I'm not sure if it's a GTK issue or if something is wrong with melonDS's GTK styles. This occurs on both the 0.7 release and on the latest git version.

```
Thread 1 "melonDS" received signal SIGSEGV, Segmentation fault.
gtk_css_style_get_value (style=0x0, id=0) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssstyle.c:74
74	  return GTK_CSS_STYLE_GET_CLASS (style)->get_value (style, id);
(gdb) bt
#0  gtk_css_style_get_value (style=0x0, id=0) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssstyle.c:74
#1  0x00007ffff7651448 in gtk_css_style_compare_next_value (change=change@entry=0x7fffffffce10) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssstylechange.c:68
#2  0x00007ffff7651598 in gtk_css_style_change_has_change (change=change@entry=0x7fffffffce10) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssstylechange.c:86
#3  0x00007ffff765f3e6 in gtk_css_widget_node_validate (node=0x55555680c6a0) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcsswidgetnode.c:127
#4  0x00007ffff764586b in gtk_css_node_validate_internal (cssnode=0x55555680c6a0, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1391
#5  0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#6  0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#7  0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#8  0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#9  0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#10 0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#11 0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#12 0x00007ffff76458cb in gtk_css_node_validate_internal (cssnode=<optimized out>, timestamp=3451296573) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcssnode.c:1398
#13 0x00007ffff762c7d6 in gtk_container_idle_sizer (clock=0x55555627e5f0, container=0x5555566602a0) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkcontainer.c:2053
#14 0x00007ffff627f02d in g_closure_invoke (closure=0x55555683efd0, return_value=0x0, n_param_values=1, param_values=0x7fffffffd180, invocation_hint=0x7fffffffd0f0)
    at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/gobject/gclosure.c:804
#15 0x00007ffff62921a3 in signal_emit_unlocked_R (node=node@entry=0x55555627d360, detail=detail@entry=0, instance=instance@entry=0x55555627e5f0, emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fffffffd180) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/gobject/gsignal.c:3635
#16 0x00007ffff629acd5 in g_signal_emit_valist (instance=0x55555627e5f0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd340) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/gobject/gsignal.c:3391
#17 0x00007ffff629b6f7 in g_signal_emit (instance=instance@entry=0x55555627e5f0, signal_id=<optimized out>, detail=detail@entry=0) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/gobject/gsignal.c:3447
#18 0x00007ffff72422ff in _gdk_frame_clock_emit_layout (frame_clock=frame_clock@entry=0x55555627e5f0) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gdk/gdkframeclock.c:634
#19 0x00007ffff72429c6 in gdk_frame_clock_paint_idle (data=0x55555627e5f0) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gdk/gdkframeclockidle.c:437
#20 0x00007ffff722dfe0 in gdk_threads_dispatch (data=0x555556431480, data@entry=<error reading variable: value has been optimized out>) at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gdk/gdk.c:743
#21 0x00007ffff5fa7343 in g_timeout_dispatch (source=source@entry=0x7fff94002450, callback=<optimized out>, user_data=<optimized out>) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/glib/gmain.c:4715
#22 0x00007ffff5fa68c5 in g_main_dispatch (context=0x555556167090) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/glib/gmain.c:3234
#23 g_main_context_dispatch (context=context@entry=0x555556167090) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/glib/gmain.c:3899
#24 0x00007ffff5fa6c88 in g_main_context_iterate (context=0x555556167090, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/glib/gmain.c:3972
#25 0x00007ffff5fa6fa2 in g_main_loop_run (loop=0x55555670f3e0) at /usr/src/debug/dev-libs/glib-2.52.3/glib-2.52.3/glib/gmain.c:4168
#26 0x00007ffff76f39b5 in gtk_main () at /usr/src/debug/x11-libs/gtk+-3.22.30/gtk+-3.22.30/gtk/gtkmain.c:1323
#27 0x0000555555597c60 in main (argc=<optimized out>, argv=0x7fffffffd778) at /usr/src/debug/games-emulation/melonds-9999/melonds-9999/src/libui_sdl/main.cpp:1598
```

**Comment by StapleButter** [comment]
this should be fixed
