### ISSUE TITLE
Crash when loading firmware

### ISSUE THREAD

**Issue by Exagone313** [Arisotura/melonDS#448]
Hi,

I just discovered your project, but I guess I built using a non-usable commit (c4182b5).
After loading a rom, or using System > Run, it crashes (`SIGSEGV`) when writing the firmware backup.
Here is a gdb backtrace: https://gist.github.com/Exagone313/a9ff271aa021b6999b7f5928e323bb24

I'm running up-to-date Arch Linux, melonDS is built like this for testing purpose (applies with a standard build too):
```
  cmake . \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_C_FLAGS_DEBUG='-g3 -O0' \
    -DCMAKE_CXX_FLAGS_DEBUG='-g3 -O0'
```

I tried other firmware binaries I could find and the same issue happens.
Looked at the code and I'm not sure how that `fwrite` could segfault.

**Comment by Arisotura** [comment]
absolutely weird

**Comment by GrieverV** [comment]
I'm also running into this issue on Arch Linux, although creating `firmware.bin.bak` manually works around it.  

melonDS: e2dc98d
OS: Arch Linux

File structure:
`/opt/melonds/melonDS`
`/opt/melonds/romlist.bin`
`$HOME/.config/melonds/bios7.bin`
`$HOME/.config/melonds/bios9.bin`
`$HOME/.config/melonds/firmware.bin`

melonDS was called using `/opt/melonds/melonDS` inside a separate 755 directory containing a ROM and the segfault occurs when attempting to open that ROM through the UI.

You can find my PKGBUILD here: [https://gitlab.com/GrieverV/PKGBUILDs/tree/master/melonds-git](https://gitlab.com/GrieverV/PKGBUILDs/tree/master/melonds-git).

Backtrace:  

    #0  0x00007ffff6c3baf2 in fwrite () at /usr/lib/libc.so.6
    #1  0x000000000045695e in SPI_Firmware::Reset() ()
        at /usr/src/debug/melonDS/src/SPI.cpp:138
            f = 0x0
            firmbkp = 0x4983e4 "firmware.bin.bak"
            userdata = <optimized out>
    #2  0x0000000000457292 in SPI::Reset() ()
        at /usr/src/debug/melonDS/src/SPI.cpp:607
    #3  0x00000000004480ee in NDS::Reset() ()
        at /usr/src/debug/melonDS/src/NDS.cpp:496
            f = <optimized out>
    #4  0x0000000000452f26 in NDSCart::LoadROM(char const*, char const*, bool)
        (path=path@entry=0x51ae80 <ROMPath> "/nds/Final Fantasy Crystal Chronicles - Echoes of Time (USA).nds", sram=sram@entry=0x51aa80 <SRAMPath> "/nds/Final Fantasy Crystal Chronicles - Echoes of Time (USA).sav", direct=<optimized out>)
        at /usr/src/debug/melonDS/src/NDSCart.cpp:880
            f = 0x1e52200
            len = <optimized out>
            gamecode = 32767
            romparams = {1620, 0, 0}
            arm9base = <optimized out>
    #5  0x00000000004473e3 in NDS::LoadROM(char const*, char const*, bool)
        (path=path@entry=0x51ae80 <ROMPath> "/nds/Final Fantasy Crystal Chronicles - Echoes of Time (USA).nds", sram=sram@entry=0x51aa80 <SRAMPath> "/nds/Final Fantasy Crystal Chronicles - Echoes of Time (USA).sav", direct=<optimized out>) at /usr/src/debug/melonDS/src/NDS.cpp:711
    #6  0x000000000041007d in TryLoadROM(char*, int) (file=file@entry=0x2006e00 "/nds/Final Fantasy Crystal Chronicles - Echoes of Time (USA).nds", prevstatus=prevstatus@entry=2) at /usr/src/debug/melonDS/src/libui_sdl/main.cpp:1620
            oldpath = '\000' <repeats 1023 times>
            oldsram = '\000' <repeats 1023 times>
    #7  0x000000000041029d in OnOpenFile(uiMenuItem*, uiWindow*, void*) (item=<optimized out>, window=<optimized out>, blarg=<optimized out>) at /usr/src/debug/melonDS/src/libui_sdl/main.cpp:1918
            prevstatus = 2
            file = 0x2006e00 "/nds/Final Fantasy Crystal Chronicles - Echoes of Time (USA).nds"
            pos = <optimized out>
    #8  0x0000000000481c84 in onClicked (menuitem=0x16e2520, data=0x175e950) at /usr/src/debug/melonDS/src/libui_sdl/libui/unix/menu.c:79
            item = 0x175e950
            w = <optimized out>
    #9  0x00007ffff7425e55 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
    #10 0x00007ffff7412ec7 in  () at /usr/lib/libgobject-2.0.so.0
    #11 0x00007ffff74170ce in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
    #12 0x00007ffff7417fb0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
    #13 0x00007ffff79d9e0b in gtk_widget_activate () at /usr/lib/libgtk-3.so.0
    #14 0x00007ffff7b14a2d in gtk_menu_shell_activate_item () at /usr/lib/libgtk-3.so.0
    #15 0x00007ffff7b17564 in  () at /usr/lib/libgtk-3.so.0
    #16 0x00007ffff7c7696c in  () at /usr/lib/libgtk-3.so.0
    #17 0x00007ffff74172d5 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
    #18 0x00007ffff7417fb0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
    #19 0x00007ffff79e0526 in  () at /usr/lib/libgtk-3.so.0
    #20 0x00007ffff7b27035 in  () at /usr/lib/libgtk-3.so.0
    #21 0x00007ffff7b2a60c in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
    #22 0x00007ffff783c514 in  () at /usr/lib/libgdk-3.so.0
    #23 0x00007ffff780bb74 in  () at /usr/lib/libgdk-3.so.0
    #24 0x00007ffff733890f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
    #25 0x00007ffff733a869 in  () at /usr/lib/libglib-2.0.so.0
    #26 0x00007ffff733b7f2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
    #27 0x00007ffff7b23bbf in gtk_main () at /usr/lib/libgtk-3.so.0
    #28 0x0000000000481724 in uiMain () at /usr/src/debug/melonDS/src/libui_sdl/libui/unix/main.c:77
    #29 0x000000000040c91d in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/melonDS/src/libui_sdl/main.cpp:2692
            ui_opt = {Size = 0}
            ui_err = <optimized out>
            whatIwant = {freq = 44100, format = 32784, channels = 1 '\001', silence = 0 '\000', samples = 1024, padding = 0, size = 0, callback = 0x40d370 <MicCallback(void*, unsigned char*, int)>, userdata = 0x0}
            whatIget = {freq = 44100, format = 32784, channels = 1 '\001', silence = 0 '\000', samples = 1024, padding = 0, size = 2048, callback = 0x40d370 <MicCallback(void*, unsigned char*, int)>, userdata = 0x0}

Arch Linux (debug) package: [melonds-git-0.8.1.r914.e2dc98d-1-x86_64.pkg.tar.xz](https://framadrop.org/r/x4SLsdtWKI#GfAjh/bhtVWnaNaeyXh5rkkh6W7OXgki31Uql2VNxAw=) (expires 2019-08-20)
