### ISSUE TITLE
Crash when saving emulator settings

### ISSUE THREAD

**Issue by potatoeggy** [Arisotura/melonDS#671]
When clicking "OK" in the "Emu settings" menu, the emulator segfaults. This does not happen when "Cancel" is clicked.

System specs:
CPU: AMD Ryzen 5 4500U
GPU: Integrated
RAM: 8 GB DDR4 @ 3200 MHz
OS: Arch Linux, kernel 5.7.7
melonDS version: commit 3827fa562fc67ae25c152a8c861c4671a68a1ccb

Steps for reproduction:
 - Open Config > Emu Settings
 - Click "OK"

```
Backtrace:
#0  0x00007ffff6762e47 in fseek () at /usr/lib/libc.so.6
#1  0x000000000041dafd in  ()
#2  0x000000000041f426 in  ()
#3  0x00007ffff6d8fa60 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff7a43ef9 in  () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff6d8fa60 in  () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff799db83 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff799e50c in  () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff799feb3 in  () at /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff79a0093 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff78edc7e in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff78ac702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff78b3977 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff6d587ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#14 0x00007ffff78b285e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff79063b2 in  () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff790978f in  () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff78ac702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff6d587ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff713337c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#20 0x00007ffff7108b4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#21 0x00007ffff3791c8c in  () at /usr/lib/libQt5XcbQpa.so.5
#22 0x00007ffff5b9943c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff5be71d9 in  () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff5b98221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#25 0x00007ffff6db1331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#26 0x00007ffff6d5713c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#27 0x00007ffff6d5f5c4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#28 0x00000000004108b8 in  ()
#29 0x00007ffff670c002 in __libc_start_main () at /usr/lib/libc.so.6
#30 0x00000000004127fe in  ()
```

**Comment by potatoeggy** [comment]
Can no longer reproduce after deleting config.
